add 'draft' status
aiidateam/AEP pull request #23
Opened 2020-11-01 22:38 UTC by ltalirz

Especially with larger projects it can take a significant amount of time
(easily a couple of months) between first discussions on an enhancement
proposal and its actual implementation/release in aiida-core.  With the
current approach, we have typically seen some initial discussion in a
pull request, which then died at some point.

Since there is no "checkpointing", when looking back at the PR after a
long time, it can be unclear what was actually agreed upon and which
questions were left open. Agreeing to merge the PR in a draft state
provides such a checkpoint (besides making the draft more visible
in the AEP repository).

We also remove the 'submitted' status, since it was used only during
the pull request stage and always needed to be changed before merging.

 - [ ] Used [AEP template](../blob/master/000_aep_guidelines/readme.md) from AEP 0
 - [ ] Status is `submitted`
 - [ ] Added type & status labels to PR
 - [ ] Added AEP to `README.md`
 - [ ] Provided github handles for authors

2020-11-02 09:38 UTC, csadorf requested changes

2020-11-02 09:38 UTC, csadorf commented on 000_aep_guidelines/readme.md
> +    * `draft` - this AEP has been accepted, and people are actively discussing and implementing it (further modifications may be necessary)
```suggestion
    * `draft` - this AEP has been accepted for further discussion and development
```
I don't think we should give the impression that a merged AEP in "draft" stage is "ready for implementation" or has received some kind of preliminary "go ahead". I would also be in favor that it still possible to reject a "draft AEP". I was under the assumption from earlier discussion that the main purpose of adding this state was to allow for AEP's to be merged so that they don't linger in PR stage limbo. I would be much less comfortable accepting an AEP into "draft" stage if this means that I can no longer ultimately reject the AEP.

IMO, whether folks work on some kind of prototype implementation in the meantime is slightly out of scope for this process (that's a management decision). For example, many PEPs are accompanied by prototype implementation to work out feasibility and implementation details that are otherwise hard to anticipate, but that certainly does not mean that those implementations can be expected to be merged.

2020-11-03 08:50 UTC, ltalirz commented on 000_aep_guidelines/readme.md
> +    * `draft` - this AEP has been accepted, and people are actively discussing and implementing it (further modifications may be necessary)
Right, I agree I should add add another review stage in between 'draft' and 'implemented'.

I'm happy to reword the description of the draft state as well, but I think it needs to reflect the fact that the gist of the AEP has been endorsed, i.e. that someone working on fleshing out the implementation of this AEP can be confident that it will be merged eventually (perhaps with changes, but not outright rejected).

2020-11-03 09:01 UTC, greschd commented on 000_aep_guidelines/readme.md
> +    * `draft` - this AEP has been accepted, and people are actively discussing and implementing it (further modifications may be necessary)
>can be confident that it will be merged eventually

I wouldn't put it quite so strongly: Yes, the accepted draft stage means that the AEP has been endorsed, and in the common case should not be rejected.

There can of course be exceptions, where during implementation we discover a significant drawback to the suggested change, that will mean the AEP still has to be rejected.

I would consider merging of a "draft" AEP as a "statement of intent" to accept the implemented AEP. A good signal that it will eventually be merged, but not a guarantee.

Of course, if the implementation of an AEP uncovers a serious flaw in our initial thinking, I also wouldn't consider that effort wasted - after all, this means that it has significantly advanced our understanding of the design space.

2020-11-03 09:05 UTC, ltalirz commented on 000_aep_guidelines/readme.md
> +    * `draft` - this AEP has been accepted, and people are actively discussing and implementing it (further modifications may be necessary)
Sounds good to me; now we just need to find a compact sentence to express this

2020-11-03 09:31 UTC, greschd commented on 000_aep_guidelines/readme.md
> +    * `draft` - this AEP has been accepted, and people are actively discussing and implementing it (further modifications may be necessary)
"this AEP has been conditionally approved; it is actively being developed, and its final version is intended to be accepted barring strong reasons for rejecting"?

2020-11-03 10:44 UTC, csadorf commented on 000_aep_guidelines/readme.md
> +    * `draft` - this AEP has been accepted, and people are actively discussing and implementing it (further modifications may be necessary)
> "this AEP has been conditionally approved; it is actively being developed, and its final version is intended to be accepted barring strong reasons for rejecting"?

That's too strong IMO. Any rejection should be backed by "strong reasons" anyways. Here is my proposal:

> This AEP has been approved for further discussion and the current state reflects the state of decisions of all parties involved.

If the discussion was well-balanced, this intrinsically means that an acceptance of AEP can be expected, but there is no reason to make it that explicit. I think we are trying to coerce governance into the state description, whereas the decision making process of AEPs hasn't even been fully clarified. Who has the authority to accept or reject AEPs? So far we've put AEPs up for discussion with the wider community and then accepted them as long as nobody voiced any concerns.

I also don't think we should be explicit on whether an AEP is implemented or not. Depending on the nature of an AEP it may or may not make sense to "work on it" prior to a final decision.

2020-11-03 22:25 UTC, ltalirz commented on 000_aep_guidelines/readme.md
> +    * `draft` - this AEP has been accepted, and people are actively discussing and implementing it (further modifications may be necessary)
My motivation for starting this discussion on the description of the draft status was that I would prefer a sentence that gives an interested developer (think e.g. an AiiDA plugin developer; a talented GSOC student; ...) some level of confidence  that if they are volunteering their precious time to work on this, it is not going to be wasted.

If I imagine myself in this position, `this AEP has been approved for further discussion` does not give me this confidence.

In my view, merging an AEP in draft state should be seen as an endorsement of this proposal by the AiiDA team, with the goal of merging an eventual implementation (to be hashed out further with the team) into AiiDA core.


> the decision making process of AEPs hasn't even been fully clarified. Who has the authority to accept or reject AEPs?

The current procedure is described in https://github.com/aiidateam/AEP/tree/master/000_aep_guidelines#how-to-submit-an-aep
It could certainly be narrowed down in more detail (e.g. currently, a PR requires 2 reviews from code owners, i.e. AiiDA team); the necessity to do this has just not arison so far.

2020-11-03 22:31 UTC, ltalirz commented on 000_aep_guidelines/readme.md
> +    * `draft` - this AEP has been accepted, and people are actively discussing and implementing it (further modifications may be necessary)
Proposed sentence: 
`this AEP is endorsed by the AiiDA team but requires further discussion and implementation`

2020-11-04 12:42 UTC, csadorf commented on 000_aep_guidelines/readme.md
> +    * `draft` - this AEP has been accepted, and people are actively discussing and implementing it (further modifications may be necessary)
> My motivation for starting this discussion on the description of the draft status was that I would prefer a sentence that gives an interested developer (think e.g. an AiiDA plugin developer; a talented GSOC student; ...) some level of confidence that if they are volunteering their precious time to work on this, it is not going to be wasted.

Quite frankly, I don't think that situation would occur in practice and this preliminary endorsement feels premature. To me AEPs are primarily a tool to document a design and then secondary a decision (approval/rejection) process. The only criterion to merge an AEP in draft stage should be whether it is generally applicable, has the right format, is of sufficient quality, and is considered "worth of a discussion" by the AiiDA team. Anything beyond that would make me personally more hesitant to merge an AEP which means we end up where we started (all drafts remain at the PR stage).

2021-12-16 23:12 UTC, ltalirz commented
Given that AEP 005 was already merged in `draft` status and we're currently lacking a formal description of it, let's move forward with this.

I've accepted the suggestion by @csadorf for the description of the `draft` status; I no longer feel as strongly about the wording as I did before, and I think is a good step forward.

2021-12-16 23:13 UTC, ltalirz commented
@sphuber please have a look; also pinged @csadorf

2021-12-16 23:59 UTC, ltalirz commented on 000_aep_guidelines/readme.md
> +  * date of creation: when the pull request for this AEP was opened
One could also use the date when the PR was merged, but I think the more interesting thing to know is how long this idea has been floating around 
+ it's how the date field has been used so far 
+ it requires less work since that way people put it in right from the beginning of the PR

2021-12-17 08:52 UTC, sphuber requested changes
Thanks @ltalirz , phrasing is fine for me. Just some small corrections to make and wondering if we should have a date that records day of merging the AEP, i.e., when it became accepted as a draft

2021-12-17 08:52 UTC, sphuber commented on 000_aep_guidelines/readme.md
> +  * date of last modification
```suggestion
  * date of last modification: should be updated whenever an implemented AEP is updated
```

2021-12-17 08:52 UTC, sphuber commented on README.md
> +<<<<<<< HEAD
```suggestion
```

2021-12-17 08:52 UTC, sphuber commented on 000_aep_guidelines/readme.md
> +  * date of last modification
Should we maybe have one more date that mentions the date when it was merged? May be overcomplicating things, but if there is a lot of time between the opening of PR and it being merged as draft for the first time, it might be useful.

It can be left empty when a PR is opened, but then as a last step before merging a new AEP, would be to update the AEP number, and set the merge and last modification date to the day of merging. Could be part of the "merging protocol".

2021-12-17 08:52 UTC, sphuber commented on 004_calcjob_importer/readme.md
> +  This might negate the benefits of the consistent import interface itself in `aiida-core`, by having differing interfaces to create the input nodes themselves, which is a prerequisite step.
Why is this line added? It seems irrelevant no?

2021-12-17 09:16 UTC, csadorf commented on 004_calcjob_importer/readme.md
> +  This might negate the benefits of the consistent import interface itself in `aiida-core`, by having differing interfaces to create the input nodes themselves, which is a prerequisite step.
Yeah, look like this change made it into wrong commit.

2021-12-17 09:20 UTC, csadorf commented on 000_aep_guidelines/readme.md
> +  * date of last modification
I feel like we should try to avoid making things more complicated here. I am already a bit hesitant about the "date of modification" considering that this already well-documented as part of the revision history and likely something that we would forget to update very regularly.

The whole AEP process is already quite bureaucratic, I would recommend to keep "procedures" and "protocols" as simple as possible.

2021-12-17 09:21 UTC, csadorf approved these changes
I'm going to approve this on the condition that the commit is cleaned up (@sphuber pointed out some artifacts). Other than that, I think this is fine as-is. I would recommend against adding the "date of modification" field, but I don't feel strongly about it and would find it more important that this PR is finally merged.

2021-12-17 09:35 UTC, sphuber commented on 000_aep_guidelines/readme.md
> +  * date of last modification
I was also not to sure about this, just wondering. So fine to leave this out.

2021-12-17 09:42 UTC, ltalirz commented on 000_aep_guidelines/readme.md
> +  * date of last modification
I'll remove it

2021-12-17 09:49 UTC, ltalirz commented on 004_calcjob_importer/readme.md
> +  This might negate the benefits of the consistent import interface itself in `aiida-core`, by having differing interfaces to create the input nodes themselves, which is a prerequisite step.
The line isn't added, it's already there - I don't see from github what the difference is, perhaps related to spaces by some editor. I guess it's fine.

2021-12-17 09:50 UTC, ltalirz commented
@sphuber Would you like to do a final check?

2021-12-17 10:33 UTC, sphuber commented on 004_calcjob_importer/readme.md
> +  This might negate the benefits of the consistent import interface itself in `aiida-core`, by having differing interfaces to create the input nodes themselves, which is a prerequisite step.
weird, ok then

2021-12-17 10:33 UTC, sphuber approved these changes

2021-12-17 10:34 UTC, merged